/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkregistro;

/**
 *
 * @author Kevin Montilla, Carlos Luna, Flavio Speziale
 * 03/07/2024
 * 
 */

public class InfoDesarrolladores extends javax.swing.JFrame {

    /**
     * Creates new form InfoProgramadores
     */
    public InfoDesarrolladores() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle(".:Información Sobre los Desarrolladores:.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblCedulaFlavio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCedulaKevin = new javax.swing.JLabel();
        lblCedulaCarlos = new javax.swing.JLabel();
        lblInfoFlavio = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblInfoKevin = new javax.swing.JLabel();
        lblInfoCarlos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mnu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSoftware = new javax.swing.JMenuItem();
        itemDesarrolladores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 39, 80));
        jPanel1.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(69, 68, 93));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(710, 30, 20, 460);

        jSeparator2.setForeground(new java.awt.Color(69, 68, 93));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(350, 30, 20, 460);

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flavio Speziale");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 300, 200, 30);

        lblCedulaFlavio.setFont(new java.awt.Font("Montserrat Light", 0, 24)); // NOI18N
        lblCedulaFlavio.setForeground(new java.awt.Color(255, 255, 255));
        lblCedulaFlavio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCedulaFlavio.setText("C.I: 31.395.251");
        jPanel1.add(lblCedulaFlavio);
        lblCedulaFlavio.setBounds(800, 330, 200, 30);

        jLabel3.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carlos Luna");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 300, 200, 30);

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kevin Montilla");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 300, 200, 30);

        lblCedulaKevin.setFont(new java.awt.Font("Montserrat Light", 0, 24)); // NOI18N
        lblCedulaKevin.setForeground(new java.awt.Color(255, 255, 255));
        lblCedulaKevin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCedulaKevin.setText("C.I: 31.363.029");
        jPanel1.add(lblCedulaKevin);
        lblCedulaKevin.setBounds(70, 330, 200, 30);

        lblCedulaCarlos.setFont(new java.awt.Font("Montserrat Light", 0, 24)); // NOI18N
        lblCedulaCarlos.setForeground(new java.awt.Color(255, 255, 255));
        lblCedulaCarlos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCedulaCarlos.setText("C.I: 32.062.856");
        jPanel1.add(lblCedulaCarlos);
        lblCedulaCarlos.setBounds(430, 330, 200, 30);

        lblInfoFlavio.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        lblInfoFlavio.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoFlavio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoFlavio.setText("<html><center>DIRECTOR DE DATOS</center></html>");
        jPanel1.add(lblInfoFlavio);
        lblInfoFlavio.setBounds(760, 390, 270, 80);

        btnRegresar.setBackground(new java.awt.Color(101, 60, 65));
        btnRegresar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("R E G R E S A R");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(420, 510, 220, 40);

        lblInfoKevin.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        lblInfoKevin.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoKevin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoKevin.setText("<html><center>DIRECTOR DE DISEÑO</center></html>");
        jPanel1.add(lblInfoKevin);
        lblInfoKevin.setBounds(40, 390, 270, 80);

        lblInfoCarlos.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        lblInfoCarlos.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoCarlos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoCarlos.setText("<html><center>DIRECTOR DE PROGRAMACIÓN</center></html>");
        jPanel1.add(lblInfoCarlos);
        lblInfoCarlos.setBounds(390, 390, 280, 80);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flavio.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(790, 30, 220, 260);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kevin.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 30, 210, 260);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/luna.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 30, 220, 260);

        mnu.setBackground(new java.awt.Color(249, 249, 249));
        mnu.setBorderPainted(false);
        mnu.setFont(new java.awt.Font("Montserrat ExtraLight", 0, 14)); // NOI18N
        mnu.setPreferredSize(new java.awt.Dimension(76, 30));

        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenu1.setHideActionText(true);

        itemSoftware.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemSoftware.setText("Software");
        itemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSoftwareActionPerformed(evt);
            }
        });
        jMenu1.add(itemSoftware);

        itemDesarrolladores.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemDesarrolladores.setText("Desarrolladores");
        itemDesarrolladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesarrolladoresActionPerformed(evt);
            }
        });
        jMenu1.add(itemDesarrolladores);

        mnu.add(jMenu1);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSoftwareActionPerformed
        InfoSoftware obj = new InfoSoftware();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSoftwareActionPerformed

    private void itemDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesarrolladoresActionPerformed
        InfoDesarrolladores obj = new InfoDesarrolladores();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemDesarrolladoresActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio obj = new Inicio();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoDesarrolladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoDesarrolladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoDesarrolladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoDesarrolladores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoDesarrolladores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenuItem itemDesarrolladores;
    private javax.swing.JMenuItem itemSoftware;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCedulaCarlos;
    private javax.swing.JLabel lblCedulaFlavio;
    private javax.swing.JLabel lblCedulaKevin;
    private javax.swing.JLabel lblInfoCarlos;
    private javax.swing.JLabel lblInfoFlavio;
    private javax.swing.JLabel lblInfoKevin;
    private javax.swing.JMenuBar mnu;
    // End of variables declaration//GEN-END:variables
}
