/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkregistro;

import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Montilla, Carlos Luna, Flavio Speziale
 * 03/07/2024
 * 
 */

public class Registro extends javax.swing.JFrame {

        Conexion conectar = Conexion.getInstance();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registro y Consultas - Trabajo Especial de Grado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlInformación1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        pnlAutor = new javax.swing.JPanel();
        lblNombreAutores = new javax.swing.JLabel();
        lblApellidoAutores = new javax.swing.JLabel();
        lblAutor1 = new javax.swing.JLabel();
        txtNombreAutor = new javax.swing.JTextField();
        txtApellidoAutor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblAutor2 = new javax.swing.JLabel();
        txtNombreAutor2 = new javax.swing.JTextField();
        txtApellidoAutor2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblAutor3 = new javax.swing.JLabel();
        txtNombreAutor3 = new javax.swing.JTextField();
        txtApellidoAutor3 = new javax.swing.JTextField();
        pnlAsesorMetodologico = new javax.swing.JPanel();
        lblNombreAsesorMetodologico = new javax.swing.JLabel();
        txtNombreAsesorMetodologico = new javax.swing.JTextField();
        lblApellidoAsesorMetodologico = new javax.swing.JLabel();
        txtApellidoAsesorMetodologico = new javax.swing.JTextField();
        pnlAsesorTecnico = new javax.swing.JPanel();
        lblNombreAsesorTecnico = new javax.swing.JLabel();
        txtNombreAsesorTecnico = new javax.swing.JTextField();
        lblApellidoAsesorTecnico = new javax.swing.JLabel();
        txtApellidoAsesorTecnico = new javax.swing.JTextField();
        pnlBuscador = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPantalla = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lblLineaInvestigacion = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        cbLineaInvestigacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaResumen = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaPalabrasClave = new javax.swing.JTextArea();
        txtAnoPresentacion = new javax.swing.JTextField();
        lblAnoPresentacion = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        mnu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSoftware = new javax.swing.JMenuItem();
        itemDesarrolladores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(40, 39, 80));

        jPanel1.setBackground(new java.awt.Color(40, 39, 80));
        jPanel1.setLayout(null);

        btnCerrarSesion.setBackground(new java.awt.Color(101, 60, 65));
        btnCerrarSesion.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("C E R R A R   S E S I Ó N");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(810, 510, 210, 30);

        pnlInformación1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true));
        pnlInformación1.setForeground(new java.awt.Color(255, 255, 255));
        pnlInformación1.setOpaque(false);
        pnlInformación1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setLabelFor(txtTitulo);
        lblTitulo.setText("TÍTULO");
        pnlInformación1.add(lblTitulo);
        lblTitulo.setBounds(10, 10, 360, 20);

        txtTitulo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });
        pnlInformación1.add(txtTitulo);
        txtTitulo.setBounds(10, 40, 358, 30);

        pnlAutor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true), "Autor(es)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Montserrat Light", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlAutor.setOpaque(false);
        pnlAutor.setLayout(null);

        lblNombreAutores.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblNombreAutores.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAutores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAutores.setLabelFor(txtNombreAutor);
        lblNombreAutores.setText("NOMBRE");
        pnlAutor.add(lblNombreAutores);
        lblNombreAutores.setBounds(40, 20, 140, 30);

        lblApellidoAutores.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblApellidoAutores.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoAutores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidoAutores.setLabelFor(txtApellidoAutor);
        lblApellidoAutores.setText("APELLIDO");
        pnlAutor.add(lblApellidoAutores);
        lblApellidoAutores.setBounds(190, 20, 140, 30);

        lblAutor1.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutor1.setText("1");
        pnlAutor.add(lblAutor1);
        lblAutor1.setBounds(10, 50, 30, 30);

        txtNombreAutor.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAutorKeyTyped(evt);
            }
        });
        pnlAutor.add(txtNombreAutor);
        txtNombreAutor.setBounds(40, 50, 140, 30);

        txtApellidoAutor.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtApellidoAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAutorKeyTyped(evt);
            }
        });
        pnlAutor.add(txtApellidoAutor);
        txtApellidoAutor.setBounds(190, 50, 140, 30);

        jSeparator1.setForeground(new java.awt.Color(69, 68, 93));
        pnlAutor.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 336, 10);

        lblAutor2.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutor2.setText("2");
        pnlAutor.add(lblAutor2);
        lblAutor2.setBounds(10, 100, 30, 30);

        txtNombreAutor2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreAutor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAutor2KeyTyped(evt);
            }
        });
        pnlAutor.add(txtNombreAutor2);
        txtNombreAutor2.setBounds(40, 100, 140, 30);

        txtApellidoAutor2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtApellidoAutor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAutor2KeyTyped(evt);
            }
        });
        pnlAutor.add(txtApellidoAutor2);
        txtApellidoAutor2.setBounds(190, 100, 140, 30);

        jSeparator3.setForeground(new java.awt.Color(69, 68, 93));
        pnlAutor.add(jSeparator3);
        jSeparator3.setBounds(10, 140, 336, 10);

        lblAutor3.setForeground(new java.awt.Color(255, 255, 255));
        lblAutor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutor3.setText("3");
        pnlAutor.add(lblAutor3);
        lblAutor3.setBounds(10, 150, 30, 30);

        txtNombreAutor3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreAutor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAutor3KeyTyped(evt);
            }
        });
        pnlAutor.add(txtNombreAutor3);
        txtNombreAutor3.setBounds(40, 150, 140, 30);

        txtApellidoAutor3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtApellidoAutor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAutor3KeyTyped(evt);
            }
        });
        pnlAutor.add(txtApellidoAutor3);
        txtApellidoAutor3.setBounds(190, 150, 140, 30);

        pnlInformación1.add(pnlAutor);
        pnlAutor.setBounds(10, 80, 360, 200);

        pnlAsesorMetodologico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true), "Asesor Metodológico", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Montserrat Light", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlAsesorMetodologico.setOpaque(false);
        pnlAsesorMetodologico.setLayout(null);

        lblNombreAsesorMetodologico.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblNombreAsesorMetodologico.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAsesorMetodologico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAsesorMetodologico.setText("NOMBRE");
        pnlAsesorMetodologico.add(lblNombreAsesorMetodologico);
        lblNombreAsesorMetodologico.setBounds(20, 30, 150, 30);

        txtNombreAsesorMetodologico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreAsesorMetodologico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAsesorMetodologicoKeyTyped(evt);
            }
        });
        pnlAsesorMetodologico.add(txtNombreAsesorMetodologico);
        txtNombreAsesorMetodologico.setBounds(20, 60, 150, 30);

        lblApellidoAsesorMetodologico.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblApellidoAsesorMetodologico.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoAsesorMetodologico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidoAsesorMetodologico.setText("APELLIDO");
        pnlAsesorMetodologico.add(lblApellidoAsesorMetodologico);
        lblApellidoAsesorMetodologico.setBounds(190, 30, 150, 30);

        txtApellidoAsesorMetodologico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtApellidoAsesorMetodologico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAsesorMetodologicoKeyTyped(evt);
            }
        });
        pnlAsesorMetodologico.add(txtApellidoAsesorMetodologico);
        txtApellidoAsesorMetodologico.setBounds(190, 60, 150, 30);

        pnlInformación1.add(pnlAsesorMetodologico);
        pnlAsesorMetodologico.setBounds(10, 290, 360, 110);

        pnlAsesorTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true), "Asesor Técnico", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Montserrat Light", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlAsesorTecnico.setOpaque(false);
        pnlAsesorTecnico.setLayout(null);

        lblNombreAsesorTecnico.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblNombreAsesorTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAsesorTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAsesorTecnico.setText("NOMBRE");
        pnlAsesorTecnico.add(lblNombreAsesorTecnico);
        lblNombreAsesorTecnico.setBounds(20, 30, 150, 30);

        txtNombreAsesorTecnico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreAsesorTecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAsesorTecnicoKeyTyped(evt);
            }
        });
        pnlAsesorTecnico.add(txtNombreAsesorTecnico);
        txtNombreAsesorTecnico.setBounds(20, 60, 150, 30);

        lblApellidoAsesorTecnico.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblApellidoAsesorTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoAsesorTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidoAsesorTecnico.setText("APELLIDO");
        pnlAsesorTecnico.add(lblApellidoAsesorTecnico);
        lblApellidoAsesorTecnico.setBounds(190, 30, 150, 30);

        txtApellidoAsesorTecnico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtApellidoAsesorTecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAsesorTecnicoKeyTyped(evt);
            }
        });
        pnlAsesorTecnico.add(txtApellidoAsesorTecnico);
        txtApellidoAsesorTecnico.setBounds(190, 60, 150, 30);

        pnlInformación1.add(pnlAsesorTecnico);
        pnlAsesorTecnico.setBounds(10, 420, 360, 110);

        jPanel1.add(pnlInformación1);
        pnlInformación1.setBounds(10, 20, 380, 540);

        pnlBuscador.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true), "Selección por ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Montserrat Light", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlBuscador.setOpaque(false);
        pnlBuscador.setLayout(null);

        txtBusqueda.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        pnlBuscador.add(txtBusqueda);
        txtBusqueda.setBounds(11, 24, 100, 30);

        btnBuscar.setBackground(new java.awt.Color(60, 61, 101));
        btnBuscar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("S E L E C C I O N A R");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlBuscador.add(btnBuscar);
        btnBuscar.setBounds(120, 20, 160, 40);

        jPanel1.add(pnlBuscador);
        pnlBuscador.setBounds(770, 20, 290, 70);

        txtPantalla.setColumns(20);
        txtPantalla.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtPantalla.setLineWrap(true);
        txtPantalla.setRows(5);
        txtPantalla.setWrapStyleWord(true);
        txtPantalla.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPantalla.setEnabled(false);
        txtPantalla.setOpaque(false);
        jScrollPane2.setViewportView(txtPantalla);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(770, 110, 290, 260);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 68, 93), 2, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        lblLineaInvestigacion.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblLineaInvestigacion.setForeground(new java.awt.Color(255, 255, 255));
        lblLineaInvestigacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineaInvestigacion.setText("LÍNEA DE INVESTIGACIÓN");
        jPanel4.add(lblLineaInvestigacion);
        lblLineaInvestigacion.setBounds(20, 10, 310, 30);

        btnRegistrar.setBackground(new java.awt.Color(60, 61, 101));
        btnRegistrar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("R E G I S T R A R");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar);
        btnRegistrar.setBounds(90, 470, 170, 50);

        cbLineaInvestigacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        cbLineaInvestigacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemáticas", "Física", "Química", "Biología", "Geología", "Ingeniería Informática", "Ingeniería Eléctrica", "Ingeniería Mecánica", "Ingeniería Civil", "Ingeniería Química", "Medicina", "Odontología", "Enfermería", "Farmacia", "Psicología", "Sociología", "Antropología", "Ciencia Política", "Economía", "Derecho", "Filosofía", "Historia", "Literatura", "Lenguas Modernas", "Artes" }));
        cbLineaInvestigacion.setSelectedIndex(-1);
        jPanel4.add(cbLineaInvestigacion);
        cbLineaInvestigacion.setBounds(20, 40, 310, 30);

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PALABRAS CLAVE");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 80, 310, 30);

        jLabel14.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("RESUMEN / ABSTRACT");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 220, 310, 30);

        txtAreaResumen.setColumns(20);
        txtAreaResumen.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtAreaResumen.setLineWrap(true);
        txtAreaResumen.setRows(5);
        txtAreaResumen.setWrapStyleWord(true);
        txtAreaResumen.setOpaque(false);
        txtAreaResumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaResumenKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtAreaResumen);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 310, 130);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");

        txtAreaPalabrasClave.setColumns(20);
        txtAreaPalabrasClave.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtAreaPalabrasClave.setLineWrap(true);
        txtAreaPalabrasClave.setRows(3);
        txtAreaPalabrasClave.setWrapStyleWord(true);
        txtAreaPalabrasClave.setOpaque(false);
        txtAreaPalabrasClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaPalabrasClaveKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtAreaPalabrasClave);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(20, 110, 310, 100);

        txtAnoPresentacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtAnoPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoPresentacionActionPerformed(evt);
            }
        });
        txtAnoPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoPresentacionKeyTyped(evt);
            }
        });
        jPanel4.add(txtAnoPresentacion);
        txtAnoPresentacion.setBounds(100, 420, 150, 30);

        lblAnoPresentacion.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        lblAnoPresentacion.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoPresentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnoPresentacion.setLabelFor(txtApellidoAutor);
        lblAnoPresentacion.setText("AÑO DE PRESENTACIÓN");
        jPanel4.add(lblAnoPresentacion);
        lblAnoPresentacion.setBounds(90, 390, 170, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(400, 20, 350, 540);

        btnConsultar.setBackground(new java.awt.Color(60, 61, 101));
        btnConsultar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("C O N S U L T A R");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setFocusPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        btnConsultar.setBounds(810, 390, 210, 30);

        btnModificar.setBackground(new java.awt.Color(60, 61, 101));
        btnModificar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("M O D I F I C A R");
        btnModificar.setBorderPainted(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setEnabled(false);
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(810, 430, 210, 30);

        btnEliminar.setBackground(new java.awt.Color(60, 61, 101));
        btnEliminar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("E L I M I N A R");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(810, 470, 210, 30);

        mnu.setBackground(new java.awt.Color(249, 249, 249));
        mnu.setBorderPainted(false);
        mnu.setFont(new java.awt.Font("Montserrat ExtraLight", 0, 14)); // NOI18N
        mnu.setPreferredSize(new java.awt.Dimension(76, 30));

        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenu1.setHideActionText(true);

        itemSoftware.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemSoftware.setText("Software");
        itemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSoftwareActionPerformed(evt);
            }
        });
        jMenu1.add(itemSoftware);

        itemDesarrolladores.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemDesarrolladores.setText("Desarrolladores");
        itemDesarrolladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesarrolladoresActionPerformed(evt);
            }
        });
        jMenu1.add(itemDesarrolladores);

        mnu.add(jMenu1);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Busca un registro en la BD
        try {

            Connection conexion = conectar.conectarBD();

            PreparedStatement buscar = conexion.prepareStatement("SELECT * FROM registro WHERE id_registro = ?");

            buscar.setString(1, txtBusqueda.getText().trim());

            ResultSet consulta = buscar.executeQuery();

            if (consulta.next()) {
                //while (consulta.next()) {
                    txtTitulo.setText(consulta.getString("titulo_registro"));
                    txtNombreAutor.setText(consulta.getString("autorNombre_1_registro"));
                    txtNombreAutor.setText(consulta.getString("autorApellido_1_registro"));
                    txtNombreAutor2.setText(consulta.getString("autorNombre_2_registro"));
                    txtNombreAutor.setText(consulta.getString("autorApellido_2_registro"));
                    txtNombreAutor3.setText(consulta.getString("autorNombre_3_registro"));
                    txtNombreAutor3.setText(consulta.getString("autorApellido_3_registro"));
                    cbLineaInvestigacion.setSelectedItem(consulta.getString("lineaIns_registro"));
                    txtAreaResumen.setText(consulta.getString("resumen_registro"));
                    txtAnoPresentacion.setText(consulta.getString("año_registro"));
                    txtNombreAsesorMetodologico.setText(consulta.getString("asesorNombreMet_registro"));
                    txtApellidoAsesorMetodologico.setText(consulta.getString("asesorApellidoMet_registro"));
                    txtNombreAsesorTecnico.setText(consulta.getString("asesorNombreTec_registro"));
                    txtApellidoAsesorTecnico.setText(consulta.getString("asesorApellidoTec_registro"));
                    txtAreaPalabrasClave.setText(consulta.getString("palabraKey_registro"));
                    //}
                JOptionPane.showMessageDialog(null, "Búsqueda exitosa");

                //Habilitar y inhabilitar botones
                btnRegistrar.setEnabled(false);
                btnEliminar.setEnabled(true);
                btnModificar.setEnabled(true);

                conectar.cerrarConexion();
            } else {
                JOptionPane.showMessageDialog(null, "Ningún trabajo de grado coincide con la búsqueda realizada", "Registro no encontrado", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            //Establecer la conexion a la BD
            Connection conexion = conectar.conectarBD();
            //Preparar la sentencia SQL de insercion
            PreparedStatement insertar = conexion.prepareStatement("insert into registro values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            insertar.setString(1,"0");
            insertar.setString(2, txtTitulo.getText().trim());
            insertar.setString(3, txtNombreAutor.getText().trim());
            insertar.setString(4, txtApellidoAutor.getText().trim());
            insertar.setString(5, txtNombreAutor2.getText().trim());
            insertar.setString(6, txtApellidoAutor2.getText().trim());
            insertar.setString(7, txtNombreAutor3.getText().trim());
            insertar.setString(8, txtApellidoAutor3.getText().trim());
            insertar.setString(9, cbLineaInvestigacion.getSelectedItem().toString());
            insertar.setString(10, txtAreaResumen.getText().trim());
            insertar.setString(11, txtAnoPresentacion.getText().trim());
            insertar.setString(12, txtNombreAsesorMetodologico.getText().trim());
            insertar.setString(13, txtApellidoAsesorMetodologico.getText().trim());
            insertar.setString(14, txtNombreAsesorTecnico.getText().trim());
            insertar.setString(15, txtApellidoAsesorTecnico.getText().trim());
            insertar.setString(16, txtAreaPalabrasClave.getText().trim());
            insertar.executeUpdate();

            JOptionPane.showMessageDialog(null,"Registro exitoso!...");

            conectar.cerrarConexion();

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Inicio obj = new Inicio();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        txtPantalla.setText("");

        try{

            Connection conexion = conectar.conectarBD();

            PreparedStatement seleccionar = conexion.prepareStatement("select * from registro");
            ResultSet consulta = seleccionar.executeQuery();

            while (consulta.next()){
                txtPantalla.append(consulta.getString(1));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(2));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(3));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(4));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(5));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(6));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(7));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(8));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(9));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(10));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(11));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(12));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(13));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(14));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(15));
                txtPantalla.append("    ");
                txtPantalla.append(consulta.getString(16));
                txtPantalla.append("    ");
                txtPantalla.append("\n");
            }
            conectar.cerrarConexion();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try{

            Connection conexion = conectar.conectarBD();

            String ID = txtBusqueda.getText().trim();
            PreparedStatement modificar = conexion.prepareStatement("UPDATE registro SET titulo_registro = ?, autorNombre_1_registro = ?, autorApellido_1_registro = ?, autorNombre_2_registro = ?, autorApellido_2_registro = ?, autorNombre_3_registro = ?, autorApellido_3_registro = ?, lineaIns_registro = ?, resumen_registro = ?, año_registro = ?, asesorNombreMet_registro = ?, asesorApellidoMet_registro = ?, asesorNombreTec_registro = ?, asesorApellidoTec_registro = ?, palabraKey_registro = ? WHERE id_registro = " + ID);

            modificar.setString(1, txtTitulo.getText().trim());
            modificar.setString(2, txtNombreAutor.getText().trim());
            modificar.setString(3, txtApellidoAutor.getText().trim());
            modificar.setString(4, txtNombreAutor2.getText().trim());
            modificar.setString(5, txtApellidoAutor2.getText().trim());
            modificar.setString(6, txtNombreAutor3.getText().trim());
            modificar.setString(7, txtApellidoAutor3.getText().trim());
            modificar.setString(8, cbLineaInvestigacion.getSelectedItem().toString());
            modificar.setString(9, txtAreaResumen.getText().trim());
            modificar.setString(10, txtAnoPresentacion.getText().trim());
            modificar.setString(11, txtNombreAsesorMetodologico.getText().trim());
            modificar.setString(12, txtApellidoAsesorMetodologico.getText().trim());
            modificar.setString(13, txtNombreAsesorTecnico.getText().trim());
            modificar.setString(14, txtApellidoAsesorTecnico.getText().trim());
            modificar.setString(15, txtAreaPalabrasClave.getText().trim());

            modificar.executeUpdate();

            JOptionPane.showMessageDialog(null, "Modificación exitosa!...");

            btnRegistrar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnConsultar.setEnabled(true);

            conectar.cerrarConexion();

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void itemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSoftwareActionPerformed
        InfoSoftware obj = new InfoSoftware();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSoftwareActionPerformed

    private void itemDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesarrolladoresActionPerformed
        InfoDesarrolladores obj = new InfoDesarrolladores();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemDesarrolladoresActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{

            Connection conexion = conectar.conectarBD();
            PreparedStatement eliminar = conexion.prepareStatement("DELETE FROM registro WHERE id_registro=?");
            
            
            Statement selectStatement = conexion.createStatement();
            ResultSet resultSet = selectStatement.executeQuery("SELECT id_registro FROM registro ORDER BY id_registro ASC");
            
            int nuevoId = 1;
            while (resultSet.next())
            {
                int idActual = resultSet.getInt("id_registro");
                PreparedStatement updateStatement = conexion.prepareStatement("UPDATE registro SET id_registro = ? WHERE id_registro = ?");
                updateStatement.setInt(1, nuevoId);
                updateStatement.setInt(2, idActual);
                updateStatement.executeUpdate();
                nuevoId++;
            }
            
            resultSet.close();
            selectStatement.close();
            
            int r = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el registro?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (r == 0) {
                eliminar.setString(1, txtBusqueda.getText().trim());
                eliminar.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro eliminado!...");

                btnRegistrar.setEnabled(true);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnConsultar.setEnabled(true);

                conectar.cerrarConexion();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        if ((txtTitulo.getText()).length()>=100){
            evt.consume();
        }
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtNombreAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAutorKeyTyped
        if ((txtNombreAutor.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreAutorKeyTyped

    private void txtApellidoAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAutorKeyTyped
        if ((txtApellidoAutor.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoAutorKeyTyped

    private void txtNombreAutor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAutor2KeyTyped
        if ((txtNombreAutor2.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreAutor2KeyTyped

    private void txtApellidoAutor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAutor2KeyTyped
        if ((txtApellidoAutor2.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoAutor2KeyTyped

    private void txtNombreAutor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAutor3KeyTyped
        if ((txtNombreAutor3.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreAutor3KeyTyped

    private void txtApellidoAutor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAutor3KeyTyped
        if ((txtApellidoAutor3.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoAutor3KeyTyped

    private void txtNombreAsesorMetodologicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAsesorMetodologicoKeyTyped
        if ((txtNombreAsesorMetodologico.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreAsesorMetodologicoKeyTyped

    private void txtApellidoAsesorMetodologicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAsesorMetodologicoKeyTyped
        if ((txtApellidoAsesorMetodologico.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoAsesorMetodologicoKeyTyped

    private void txtNombreAsesorTecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAsesorTecnicoKeyTyped
        if ((txtNombreAsesorTecnico.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreAsesorTecnicoKeyTyped

    private void txtApellidoAsesorTecnicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAsesorTecnicoKeyTyped
        if ((txtApellidoAsesorTecnico.getText()).length()>=15){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoAsesorTecnicoKeyTyped

    private void txtAnoPresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoPresentacionKeyTyped
        char tecla;
        
        tecla = evt.getKeyChar();
        
        if (tecla < '0' || tecla > '9') evt.consume();
        
        if ((txtAnoPresentacion.getText()).length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoPresentacionKeyTyped

    private void txtAreaPalabrasClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaPalabrasClaveKeyTyped
        if ((txtAreaPalabrasClave.getText()).length()>=50){
            evt.consume();
        }
    }//GEN-LAST:event_txtAreaPalabrasClaveKeyTyped

    private void txtAreaResumenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaResumenKeyTyped
        if ((txtAreaResumen.getText()).length()>=1000){
            evt.consume();
        }
    }//GEN-LAST:event_txtAreaResumenKeyTyped

    private void txtAnoPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoPresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoPresentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbLineaInvestigacion;
    private javax.swing.JMenuItem itemDesarrolladores;
    private javax.swing.JMenuItem itemSoftware;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAnoPresentacion;
    private javax.swing.JLabel lblApellidoAsesorMetodologico;
    private javax.swing.JLabel lblApellidoAsesorTecnico;
    private javax.swing.JLabel lblApellidoAutores;
    private javax.swing.JLabel lblAutor1;
    private javax.swing.JLabel lblAutor2;
    private javax.swing.JLabel lblAutor3;
    private javax.swing.JLabel lblLineaInvestigacion;
    private javax.swing.JLabel lblNombreAsesorMetodologico;
    private javax.swing.JLabel lblNombreAsesorTecnico;
    private javax.swing.JLabel lblNombreAutores;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JPanel pnlAsesorMetodologico;
    private javax.swing.JPanel pnlAsesorTecnico;
    private javax.swing.JPanel pnlAutor;
    private javax.swing.JPanel pnlBuscador;
    private javax.swing.JPanel pnlInformación1;
    private javax.swing.JTextField txtAnoPresentacion;
    private javax.swing.JTextField txtApellidoAsesorMetodologico;
    private javax.swing.JTextField txtApellidoAsesorTecnico;
    private javax.swing.JTextField txtApellidoAutor;
    private javax.swing.JTextField txtApellidoAutor2;
    private javax.swing.JTextField txtApellidoAutor3;
    private javax.swing.JTextArea txtAreaPalabrasClave;
    private javax.swing.JTextArea txtAreaResumen;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombreAsesorMetodologico;
    private javax.swing.JTextField txtNombreAsesorTecnico;
    private javax.swing.JTextField txtNombreAutor;
    private javax.swing.JTextField txtNombreAutor2;
    private javax.swing.JTextField txtNombreAutor3;
    private javax.swing.JTextArea txtPantalla;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
