/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkregistro;

/**
 *
 * @author Kevin Montilla, Carlos Luna, Flavio Speziale
 * 03/07/2024
 * 
 */

public class TerminosYCondiciones extends javax.swing.JFrame {

    /**
     * Creates new form TerminosYCondiciones
     */
    
    public TerminosYCondiciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle(".:Términos y Condiciones:.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaTerminosYCondiciones = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        cbAceptarTerminosYCondiciones = new javax.swing.JCheckBox();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSoftware = new javax.swing.JMenuItem();
        itemDesarrolladores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 39, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 550));
        jPanel1.setLayout(null);

        jScrollPane1.setEnabled(false);

        txtareaTerminosYCondiciones.setEditable(false);
        txtareaTerminosYCondiciones.setColumns(1);
        txtareaTerminosYCondiciones.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        txtareaTerminosYCondiciones.setForeground(new java.awt.Color(40, 39, 80));
        txtareaTerminosYCondiciones.setLineWrap(true);
        txtareaTerminosYCondiciones.setRows(1);
        txtareaTerminosYCondiciones.setText("1)     Prohibida la venta o distribución del software sin la debida autorización.\n\n2)     Prohibida la alteración del código fuente o el diseño de las interfaces gráficas de usuario.\n\n3)     El autor no se hace responsable del mal uso de este software. Los acuerdos legales expuestos seguidamente rigen el uso que usted haga de este software. El autor no se responsabiliza del uso que usted haga de este software y sus servicios. \n\nPara aceptar los términos haga clic en la casilla que acompaña su nombre con la palabra Acepto y,a continuación, presione el botón Continuar. Para mayor información sobre nuestros productos y servicios, lo invitamos a visitar nuestra página web accediendo a la siguiente url: \n\nhttp://unsitio.com.ve");
        txtareaTerminosYCondiciones.setWrapStyleWord(true);
        txtareaTerminosYCondiciones.setCaretPosition(0);
        txtareaTerminosYCondiciones.setDisabledTextColor(new java.awt.Color(110, 110, 135));
        txtareaTerminosYCondiciones.setEnabled(false);
        txtareaTerminosYCondiciones.setMargin(new java.awt.Insets(15, 10, 10, 10));
        txtareaTerminosYCondiciones.setName(""); // NOI18N
        txtareaTerminosYCondiciones.setOpaque(false);
        jScrollPane1.setViewportView(txtareaTerminosYCondiciones);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(42, 105, 630, 290);

        lblTitulo.setFont(new java.awt.Font("Montserrat Black", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TÉRMINOS Y CONDICIONES");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(120, 30, 550, 44);

        cbAceptarTerminosYCondiciones.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        cbAceptarTerminosYCondiciones.setForeground(new java.awt.Color(255, 255, 255));
        cbAceptarTerminosYCondiciones.setText("HE LEÍDO Y ACEPTO LOS TÉRMINOS Y CONDICIONES");
        cbAceptarTerminosYCondiciones.setBorderPaintedFlat(true);
        cbAceptarTerminosYCondiciones.setFocusPainted(false);
        cbAceptarTerminosYCondiciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbAceptarTerminosYCondicionesStateChanged(evt);
            }
        });
        cbAceptarTerminosYCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAceptarTerminosYCondicionesActionPerformed(evt);
            }
        });
        jPanel1.add(cbAceptarTerminosYCondiciones);
        cbAceptarTerminosYCondiciones.setBounds(190, 420, 353, 19);

        btnRegresar.setBackground(new java.awt.Color(101, 60, 65));
        btnRegresar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("R E G R E S A R");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(120, 460, 210, 40);

        btnContinuar.setBackground(new java.awt.Color(95, 95, 125));
        btnContinuar.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("C O N T I N U A R");
        btnContinuar.setBorderPainted(false);
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.setEnabled(false);
        btnContinuar.setFocusPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(390, 460, 210, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vigilancia.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 26, 50, 60);

        mnu.setBackground(new java.awt.Color(249, 249, 249));
        mnu.setBorderPainted(false);
        mnu.setFont(new java.awt.Font("Montserrat ExtraLight", 0, 14)); // NOI18N
        mnu.setPreferredSize(new java.awt.Dimension(76, 30));

        jMenu1.setText("Acerca de");
        jMenu1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenu1.setHideActionText(true);

        itemSoftware.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemSoftware.setText("Software");
        itemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSoftwareActionPerformed(evt);
            }
        });
        jMenu1.add(itemSoftware);

        itemDesarrolladores.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        itemDesarrolladores.setText("Desarrolladores");
        itemDesarrolladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesarrolladoresActionPerformed(evt);
            }
        });
        jMenu1.add(itemDesarrolladores);

        mnu.add(jMenu1);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAceptarTerminosYCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAceptarTerminosYCondicionesActionPerformed
        
    }//GEN-LAST:event_cbAceptarTerminosYCondicionesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio obj = new Inicio();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbAceptarTerminosYCondicionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbAceptarTerminosYCondicionesStateChanged
        // Identifica si el CheckBox ha sido seleccionado
        if (cbAceptarTerminosYCondiciones.isSelected() == true){
            btnContinuar.setEnabled(true);  //Habilita el boton
        } else {
            btnContinuar.setEnabled(false);  //Inhabilita el boton
        }
    }//GEN-LAST:event_cbAceptarTerminosYCondicionesStateChanged

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        Registro obj = new Registro();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void itemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSoftwareActionPerformed
        InfoSoftware obj = new InfoSoftware();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSoftwareActionPerformed

    private void itemDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesarrolladoresActionPerformed
        InfoDesarrolladores obj = new InfoDesarrolladores();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemDesarrolladoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminosYCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminosYCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminosYCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminosYCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminosYCondiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox cbAceptarTerminosYCondiciones;
    private javax.swing.JMenuItem itemDesarrolladores;
    private javax.swing.JMenuItem itemSoftware;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JTextArea txtareaTerminosYCondiciones;
    // End of variables declaration//GEN-END:variables
}
